apiVersion: v1
kind: Service
metadata:
  name: barnacle-back
  labels:
    app: barnacle-back
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      nodePort: 30003
  selector:
    app: barnacle-back
