apiVersion: apps/v1
kind: Deployment
metadata:
  name: barnacle-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barnacle-back
  template:
    metadata:
      labels:
        app: barnacle-back
    spec:
      containers:
        - name: barnacle-back
          image: 172.30.1.1:5000/barnacle/barnacle-back:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MONGO_HOST
              value: "mongodb.barnacle.svc"